### ISSUE TITLE
Run code coverage on smart contracts

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1225]
This involves running `forge coverage`, probably with `--report lcov` and then uploading the file to coveralls.

```yaml
      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
```

We probably don't want to run this on every PR but on pushes to `main`.
