### ISSUE TITLE
Environment variable versioning

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/espresso-sequencer#2359]
Improve the UX when we change or remove environment variables. Specifically,
* when we rename an environment variable, the old name should be valid and considered a synonym for the new name for at least one release. During this time, if the old name is set, we should print a warning like "{old_name} is deprecated, use {new_name} instead. This will be an error in a future release". If in addition the new variable is not set, it should get its value from the old variable
* when we remove an environment variable, if it is still set, we should print a warning like "{deprecated_var} is no longer supported and will be ignored", and in addition print variable-specific information about how to update their config

In implementing this, we want to avoid separate ad-hoc code that needs to be changed or added every time we remove or change an environment variable. Thus, we suggest creating a config file like `env-vars.toml`. It could have a format like this

```toml
# Variables in this section print a warning and automatically treat the old name as an alias for the new name.
[[deprecated]]
old = "ESPRESSO_SEQUENCER_POSTGRES_MIN_CONNECTIONS"
new = "ESPRESSO_SEQUENCER_DATABASE_MIN_CONNECTIONS"

# Variables in this section give an error if used. Variables are moved from deprecated to replaced after at least one release.
[[replaced]]
old = "ESPRESSO_SEQUENCER_POSTGRES_MIN_CONNECTIONS"
new = "ESPRESSO_SEQUENCER_DATABASE_MIN_CONNECTIONS"

# Variables in this section have no direct replacement, but give a warning and an optional suggestion if used.
[[deleted]]
name = "UNSUPPORTED_VAR"
help = "What do we recommend people to do who were making use of UNSUPPORTED_VAR"
```

We can then have just one piece of code that parses this file, looks at all the environment variables which are set, and takes the appropriate action. This function could be invoked at the start of every `main` function just before parsing clap options.
