### ISSUE TITLE
Investigate why L1 container is recreated

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#251]
When we run docker compose a second time to start the zkevm services after deploying contracts the L1 container is restarted and therefore doesn't contain the deployed contracts anymore.

This currenly happens on my computer and if I remove the dependency 
```
  zkevm-permissionless-node:
  ...
    depends_on:
      zkevm-mock-l1-network:
        condition: service_started
```
the problem disappears.

Since this did not happen earlier I wonder if it's related to changes in docker.
